### ISSUE TITLE
tokei.rs badges always show 0 lines of code

### ISSUE THREAD

**Issue by svenstaro** [XAMPPRocky/tokei#942] opened 2022-09-07 04:59 UTC
Since a while now, the badges from tokei.rs are showing 0 lines of code. This is even true for this very project:
![image](https://user-images.githubusercontent.com/1664/188792302-28b6f987-fafe-47ea-a913-436f659be938.png)

**Comment by 3kh0** [comment] 2022-09-08 17:55
Duplicate of #881

**Comment by XAMPPRocky** [comment] 2022-09-09 07:27
Thank you for your issue! Closing as duplicate

**Closed by XAMPPRocky** 2022-09-09 07:27 UTC
