### ISSUE TITLE
C code line count fails if starts with /*\ or ends with \*/

### ISSUE THREAD

**Issue by PurpleMyst** [XAMPPRocky/tokei#465] opened 2020-03-17 06:26 UTC
# Minimal Example

Save this as file `bug.c`

```c
/*\ foo \*/
int main(void) {}
```

# Actual Output

```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 C                       1            2            0            2            0
-------------------------------------------------------------------------------
 Total                   1            2            0            2            0
-------------------------------------------------------------------------------
```

# Command Ran

    tokei -f bug.c

# Expected Output

```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 C                       1            2            1            1            0
-------------------------------------------------------------------------------
 Total                   1            2            1            1            0
-------------------------------------------------------------------------------
```

**Comment by XAMPPRocky** [comment] 2020-03-17 08:03
Thank you for your issue! I'm going to close this as a duplicate of #398

**Closed by XAMPPRocky** 2020-03-17 08:03 UTC

**Comment by PurpleMyst** [comment] 2020-03-17 10:24
Ah alright sorry, it wasn't in the "this issue is similiar to ..." page so I assumed it was novel.
