### ISSUE TITLE
Asciinema recording will be archived soon

### ISSUE THREAD

**Issue by Darksonn** [XAMPPRocky/tokei#290] opened 2019-01-13 22:10 UTC
I clicked the recording in the README to view it and saw the following message in the header of the page:

> This recording will be archived soon. More details: blog.asciinema.org/post/archival/

You should probably follow their instructions to ensure the recording isn't removed.

**Comment by Porkepix** [comment] 2019-02-10 22:06
It have now been archived and therefore can't bee watched anymore.

**Comment by alexreg** [comment] 2019-03-04 22:59
@Aaronepower I trust you're aware of this? :-)

**Comment by Aaronepower** [comment] 2019-03-05 07:30
Thank you for this issue! Yes I am aware of this, and I just haven't had the time to create a gif to embed into the GitHub page. If someone has a high quality gif of tokei running in its own directory I would be happy to use that.

**Comment by LovecraftianHorror** [comment] 2019-11-24 18:06
Are there several commands you would want demonstrated, or would a screenshot of `tokei`'s output also be sufficient?

**Comment by XAMPPRocky** [comment] 2019-11-24 22:40
Sorry for not updating this, I have since made several attempts at a high quality gif to replace the original asciiema recording, however the problem is that the gif would be so large for the quality I would want. I'm going to close this issue and file a new one.

**Closed by XAMPPRocky** 2019-11-24 22:40 UTC
Labels: help wanted
