### ISSUE TITLE
tokei mistakes V code for Coq code

### ISSUE THREAD

**Issue by mark-summerfield** [XAMPPRocky/tokei#764] opened 2021-05-04 08:27 UTC
The [V language](https://vlang.io/) (like Coq) uses a `.v` extension, but surely it is possible for tokei to distinguish the two?

**Comment by cake4289** [comment] 2021-05-14 08:33
This is also an issue for Verilog code, which also uses a `.v` extension, and is probably more common than both Coq and V.

**Comment by XAMPPRocky** [comment] 2021-05-14 08:38
Thank you for your issue! I'm going to close this as a duplicate of #67. In short, no but I hope to add it soon.

**Closed by XAMPPRocky** 2021-05-14 08:38 UTC
