### ISSUE TITLE
Add digit grouping for better readability when displaying large numbers

### ISSUE THREAD

**Issue by aa-ko** [XAMPPRocky/tokei#552] opened 2020-06-02 22:37 UTC
I feel like the default plain text output of tokei gets hard to read when the number of lines goes above 5 or 6 digits. I'd suggest implementing some kind of digit grouping like this:
```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 BASH                    4           49           30           10            9
 JSON                    1        1,259        1,259            0            0
 Markdown                4        1,266        1,266            0            0
 Rust                   19        3,117        2,271          446          400
 Shell                   1           49           38            1           10
 TOML                    1           80           69            0           11
-------------------------------------------------------------------------------
 Total                  30        5,820        4,933          457          430
-------------------------------------------------------------------------------
```

This change would only make sense for plain text output, JSON/YAML/etc. output formats would remain unchanged.
I also thought about how the system locale might play a role in this. I am German and thus would naturally use a `.` as the digit group delimiter.

Please let me know if this is something you'd be interested to see being implemented.

**Comment by XAMPPRocky** [comment] 2020-06-02 22:49
Thank you for your issue! However this is a duplicate of #256 so I'm going to close this one.

**Closed by XAMPPRocky** 2020-06-02 22:49 UTC
