### ISSUE TITLE
.tokeirc configuration file

### ISSUE THREAD

**Issue by XAMPPRocky** [XAMPPRocky/tokei#195] opened 2018-02-22 13:57 UTC
## Currently requested features

- [ ] #194 Add languages
- [ ] #67 Map existing languages to different extensions.

**Comment by weihanglo** [comment] 2018-04-18 15:42
What format would be chosen for this configuration file? Something like .gitignore or YAML/TOML?

**Comment by Aaronepower** [comment] 2018-04-18 17:07
@weihanglo I'm currently leaning towards TOML to be in line with tools like rustfmt and to allow complex options to be defined. Such as treating python's `"""string"""` quotes as comments.

**Comment by remexre** [comment] 2019-02-20 08:56
#67 is marked as done in the OP, but I can't find docs on how to do this. Specifically, I want `.f` files to be Forth instead of Fortran.

**Comment by Aaronepower** [comment] 2019-02-20 11:59
@remexre Sorry, that feature was actually pulled from 9.0 as right now `toml` will not deserialize at type of `HashMap<Enum, HashMap<String, String>>` the problem is the current enum support, so it is blocked on that. Sorry for the incorrect information, I've updated this post and hidden the comment in #67.

**Closed** 2020-05-30 13:21 UTC
Labels: enhancement
