### ISSUE TITLE
tokei could be better with `.y` files

### ISSUE THREAD

**Issue by anahata0108** [XAMPPRocky/tokei#767] opened 2021-05-17 21:12 UTC
Hello! The version of tokei I installed via cargo (12.1.1) is incorrectly identifying .y files (for the yacc / bison parser generators) as Happy source code. It looks like the correct way to approach a fix for this is to specify the comment types in the languages.json file. 

I'm willing to make these changes, but I'm not sure where to find information about the Happy language. It's hard to search for given the name. Is it [this](https://www.haskell.org/happy/doc/html/index.html) Haskell parser generator? A brief, nonexhaustive glance at the documentation doesn't yield any information about comments in that language. 

Conversely, we do know the kind of comments that Bison and Yacc use, so adding information there should be easy enough.

Do I understand this correctly? If so, I can get a PR up soon. I just want to be sure I understand correctly before filing a useless PR. :)

**Comment by brightly-salty** [comment] 2021-06-16 18:04
As far as I know, Happy (which is a parser generator written in Haskell, yes) would use the same comment syntax as Haskell. `--` for single line and `{-`/`-}` for multi-line comments.

**Comment by XAMPPRocky** [comment] 2021-06-17 07:30
Thank you for your issue! I'm going to close this as a duplicate of #67. In short, yes I would like to support this, but I want to provide the way to change at runtime, as I don't want tokei to flip what extension is counted as what between versions unless it's a bug, and while it might be unintuitive that the extension is not mapped onto a language you'd expect, I don't consider that a bug.

**Closed by XAMPPRocky** 2021-06-17 07:30 UTC
